# Generated by Django 4.1.7 on 2023-04-22 16:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import lc_app.templatetags.extras


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('title_ar', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=400)),
                ('phone', models.CharField(editable=False, max_length=400)),
                ('details', models.CharField(editable=False, max_length=400)),
                ('read', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('address_ar', models.CharField(max_length=1000)),
                ('phone_1', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('phone_2', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Office', max_length=100)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=400)),
                ('phone', models.CharField(editable=False, max_length=400)),
                ('date', models.CharField(editable=False, max_length=400)),
                ('details', models.CharField(editable=False, max_length=400)),
                ('car', models.CharField(editable=False, max_length=400)),
                ('read', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PagesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_ar', models.TextField()),
                ('banner', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('pages_banners'))),
            ],
        ),
        migrations.CreateModel(
            name='Service_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('title_ar', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_ar', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=1000)),
                ('platform', models.CharField(choices=[('facebook', 'FaceBook'), ('whatsapp', 'Whats App'), ('phone', 'Mobile'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], default='facebook', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200)),
                ('quote', models.CharField(max_length=500)),
                ('quote_ar', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('title_ar', models.CharField(max_length=200, unique=True)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=0.5, size=[300, 400], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services'))),
                ('banner', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=0.5, size=[1920, 1080], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_banner'))),
                ('summary', models.CharField(max_length=100)),
                ('summary_ar', models.CharField(max_length=100)),
                ('slider_image_1', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=80, scale=0.5, size=[1000, 800], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_Slider_1'))),
                ('slider_image_2', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=80, scale=0.5, size=[1000, 800], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_Slider_2'))),
                ('description', models.TextField()),
                ('description_ar', models.TextField()),
                ('description2', models.TextField(default='random text')),
                ('description2_ar', models.TextField(default='random text')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc_app.service_category')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200)),
                ('model', models.PositiveIntegerField(default=1990, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2023)])),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=0.5, size=[200, 150], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('cars'))),
                ('person_count', models.PositiveIntegerField(default=1)),
                ('bag_count', models.PositiveIntegerField(default=1)),
                ('reserve_days', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lc_app.car_category')),
            ],
        ),
    ]
