# Generated by Django 4.1.7 on 2023-04-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=400)),
                ('phone', models.CharField(editable=False, max_length=400)),
                ('details', models.CharField(editable=False, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=400)),
                ('phone', models.CharField(editable=False, max_length=400)),
                ('date', models.CharField(editable=False, max_length=400)),
                ('details', models.CharField(editable=False, max_length=400)),
                ('car', models.CharField(editable=False, max_length=400)),
            ],
        ),
    ]
