# Generated by Django 4.1.7 on 2023-04-23 09:44

from django.db import migrations
import django_resized.forms
import lc_app.templatetags.extras


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=0.5, size=[300, 400], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_thumbnail')),
        ),
    ]
