# Generated by Django 4.1.7 on 2023-04-23 12:35

from django.db import migrations
import django_resized.forms
import lc_app.templatetags.extras


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0002_alter_service_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=80, scale=1, size=[500, 300], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('cars')),
        ),
        migrations.AlterField(
            model_name='pagesinfo',
            name='banner',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1, size=[1920, 1080], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('pages_banners')),
        ),
        migrations.AlterField(
            model_name='service',
            name='banner',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1, size=[1920, 1080], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_banner')),
        ),
        migrations.AlterField(
            model_name='service',
            name='slider_image_1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1, size=[1920, 1080], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_Slider_1')),
        ),
        migrations.AlterField(
            model_name='service',
            name='slider_image_2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1, size=[1920, 1080], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_Slider_2')),
        ),
        migrations.AlterField(
            model_name='service',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, scale=1, size=[1920, 1080], storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_thumbnail')),
        ),
    ]
