# Generated by Django 4.1.7 on 2023-04-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0002_complain_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='read',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='read',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
