# Generated by Django 4.1.7 on 2023-04-22 14:57

from django.db import migrations, models
import lc_app.templatetags.extras


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0003_complain_read_order_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description2',
            field=models.TextField(default='random text'),
        ),
        migrations.AddField(
            model_name='service',
            name='description2_ar',
            field=models.TextField(default='random text'),
        ),
        migrations.AlterField(
            model_name='map',
            name='location_name',
            field=models.CharField(default='Office', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='slider_image_1',
            field=models.ImageField(storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_Slider_1')),
        ),
        migrations.AlterField(
            model_name='service',
            name='slider_image_2',
            field=models.ImageField(storage=lc_app.templatetags.extras.OverwriteStorage(), upload_to=lc_app.templatetags.extras.PathRename('services', '_Slider_2')),
        ),
    ]
