# Generated by Django 4.1.7 on 2023-04-24 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0003_alter_car_image_alter_pagesinfo_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2023)])),
                ('description', models.TextField()),
                ('description_ar', models.TextField()),
            ],
        ),
    ]
