# Generated by Django 4.1.7 on 2023-04-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0005_alter_social_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='العنوان'),
        ),
    ]
