# Generated by Django 4.1.7 on 2023-04-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0006_alter_service_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمة', 'verbose_name_plural': 'خدمات'},
        ),
    ]
