# Generated by Django 4.1.7 on 2023-04-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0007_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
