# Generated by Django 4.1.7 on 2023-04-29 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_app', '0008_alter_service_options_alter_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_1',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_2',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
